/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package project.euler;

/*Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */
public class Problem2 {

    /**
     *
     * @param args
     */
    public static void main(String[] args) {
        int n1 = 0;
        int n2 = 1;
        int n3;
        n3 = n1 + n2;
        int sum = 0;
        
        while (n3 < 4000000) {
            n1 = n2;
            if (n3 % 2 == 0) {
                sum = sum + n3;
            }
            n2 = n3;
            n3 = n1 + n2;
        }
        
        System.out.println(sum);
    }
}
